PhysicalTherapyProjectV2/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using PhysicalTherapyProject.Application.Infrastructure;
using PhysicalTherapyProject.Application.Infrastructure.Enums;
using PhysicalTherapyProject.Application.Infrastructure.Extensions;
using PhysicalTherapyProject.Application.Infrastructure.Interfaces;
using PhysicalTherapyProject.Application.Models.ViewModels;
using PhysicalTherapyProject.Domain.Models;
using PhysicalTherapyProject.Persistance.Infrastructure.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PhysicalTherapyProjectV2.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IUserRepository _userRepository;
        private readonly IGenericRepository<Tag> _tagRepository;
        private readonly IPostService _postService;

        public AdminController(IPostRepository postRepository, IUserRepository userRepository,
            IGenericRepository<Tag> tagRepository, IPostService postService)
        {
            _postRepository = postRepository;
            _userRepository = userRepository;
            _tagRepository = tagRepository;
            _postService = postService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userRepository.GetAllAsync());
        }

        #region EVENT
        [HttpGet]
        public async Task<IActionResult> ListEvent()
           => View(await _postRepository.GetAllByTypeAsync((int)PostTypes.Event));

        [HttpGet]
        public IActionResult CreateEvent() => View(new PostViewModel
        {
            Post = new Post() { PostTypeId = 2 }
        });

        [HttpGet]
        public async Task<IActionResult> EditEvent(int id) =>
            View(nameof(CreateEvent), new PostViewModel()
            {
                Post = await _postRepository.GetByIdAsync(id)
            });


        [HttpPost]
        public async Task<IActionResult> DeleteEvent(int id)
        {
            var article = await _postRepository.GetByIdAsync(id);
            await _postRepository.DeleteAsync(id);
            TempData["message"] = $"Renginys '{article.Title}' buvo ištrintas!";
            return RedirectToAction(nameof(ListEvent));
        }
        #endregion

        #region TEAMMEMBER
        public IActionResult CreateTeamMember() => View(new PostViewModel
        {
            Post = new Post() { PostTypeId = (int)PostTypes.TeamMember }
        });

        public async Task<IActionResult> ListTeamMembers() =>
            View(await _postRepository.GetAllByTypeAsync((int)PostTypes.TeamMember));

        [HttpGet]
        public async Task<IActionResult> EditTeamMembers(int id) =>
        View(nameof(CreateTeamMember), new PostViewModel()
        {
            Post = await _postRepository.GetByIdAsync(id)
        });

        [HttpPost]
        public async Task<IActionResult> DeleteTeamMembers(int id)
        {
            var article = await _postRepository.GetByIdAsync(id);
            await _postRepository.DeleteAsync(id);
            TempData["message"] = $"Informacija apie komandos narį '{article.Title}' buvo ištrinta!";
            return RedirectToAction(nameof(ListTeamMembers));
        }
        #endregion

        #region ARTICLE
        public async Task<IActionResult> ListArticle() =>
            View(await _postRepository.GetAllByTypeAsync((int)PostTypes.Article));

        public async Task<IActionResult> CreateArticle()
        {
            var tags = await _tagRepository.GetAllAsync();
            return View(new PostViewModel
            {
                Post = new Post() { PostTypeId = (int)PostTypes.Article },
                Tags = tags.ConvertToSelectListItems()
            });
        }

        [HttpGet]
        public async Task<IActionResult> EditArticle(int id)
        {
            var tags = await _tagRepository.GetAllAsync();
            return View(nameof(CreateArticle), new PostViewModel()
            {
                Post = await _postRepository.GetByIdAsync(id),
                Tags = tags.ConvertToSelectListItems()
            });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteArticle(int id)
        {
            var article = await _postRepository.GetByIdAsync(id);
            await _postRepository.DeleteAsync(id);
            TempData["message"] = $"Straipsnis '{article.Title}' buvo ištrintas!";
            return RedirectToAction(nameof(ListArticle));
        }
        #endregion

        #region USER
        [HttpPost]
        public async Task<IActionResult> ConfirmUser(int userId)
        {
            var user = await _userRepository.GetByIdAsync(userId);
            user.IsConfirmed = true;
            await _userRepository.UpdateAsync(user);
            TempData["message"] = $"{user.Name} {user.Surname} buvo patvirtintas!";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(int userId)
        {
            var user = await _userRepository.GetByIdAsync(userId);
            await _userRepository.DeleteAsync(userId);
            TempData["message"] = $"{user.Name} {user.Surname} buvo ištrintas!";
            return RedirectToAction(nameof(Index));
        }
        #endregion

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel.CurrentView, viewmodel);
            }

            try
            {
                await _postService.CreatePostAsync(viewmodel);
                TempData["message"] = _postService.ServiceMessage;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("File Error", ex.Message);
                return View(viewmodel.CurrentView, viewmodel);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

PhysicalTherapyProjectV2/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using PhysicalTherapyProject.Application.Infrastructure.Enums;
using PhysicalTherapyProject.Domain.Models;
using PhysicalTherapyProject.Persistance.Infrastructure.Interfaces;

namespace PhysicalTherapyProjectV2.Controllers
{
    [Authorize]
    public class ArticleController : BasePostController
    {
        public ArticleController(IPostRepository _postRepository,
            SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
            : base(_postRepository, (int)PostTypes.Article, signInManager, userManager) { }

    }
}

PhysicalTherapyProjectV2/Controllers/EventController.cs
using Microsoft.AspNetCore.Identity;
using PhysicalTherapyProject.Application.Infrastructure.Enums;
using PhysicalTherapyProject.Domain.Models;
using PhysicalTherapyProject.Persistance.Infrastructure.Interfaces;

namespace PhysicalTherapyProjectV2.Controllers
{
    public class EventController : BasePostController
    {
        public EventController(IPostRepository _postRepository,
            SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
            : base(_postRepository, (int)PostTypes.Event, signInManager, userManager)
        { }
    }
}

PhysicalTherapyProjectV2/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/admin-panel-styles.css">
    <link rel="stylesheet" type="text/css" href="~/css/main-style.css">
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    @RenderSection("Stylesheets", required: false)

</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <h3 class="navbar-brand">
            Administratoriaus Panelė
        </h3>
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">

                <div class="input-group-append">
                    <a asp-action="Index" asp-controller="Home" class="btn btn-full" type="button">Sugrįžti į pagrindinį puslapį</a>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Vaizdas Iš Viršaus</div>
                        <a class="nav-link" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Apžvalga
                        </a>
                        <div class="sb-sidenav-menu-heading">Veiksmai</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                           aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Mokėjimai
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Visi</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Nauji</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Tvarkyti Informaciją
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" aria-expanded="false" asp-action="ListArticle">
                                    Peržiūrėti Straipsnius
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>
                                <a class="nav-link" aria-expanded="false" asp-action="CreateArticle">
                                    Kurti Straipsnį
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>

                                <a class="nav-link" aria-expanded="false" asp-action="ListEvent">
                                    Peržiūrėti Renginius
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>
                                <a class="nav-link" aria-expanded="false" asp-action="CreateEvent">
                                    Kurti Renginį
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>

                                <a class="nav-link" aria-expanded="false" asp-action="ListTeamMembers">
                                    Peržiūrėti Valdybos Narius
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>
                                <a class="nav-link" aria-expanded="false" asp-action="CreateTeamMember">
                                    Pridėti Valdybos Narius
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-right"></i></div>
                                </a>

                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Papildymai</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                @if (User.Identity.Name != null)
                {
                    <div class="sb-sidenav-footer">
                        <div class="small">Jūs esate prisijungęs kaip:</div>
                        @User.Identity.Name.ToLower()
                    </div>
                }
            </nav>
        </div>
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/datatables-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PhysicalTherapyProjectV2/Views/Shared/_AlertBoxPartial.cshtml
@model string
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    <p>@Model</p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

PhysicalTherapyProjectV2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="lt">
<head>
    <link rel="stylesheet" type="text/css" href="~/css/cms-styles.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/grid.css">
    <link rel="stylesheet" type="text/css" href="~/css/main-style.css">
    <link rel="stylesheet" type="text/css" href="~/css/AboutUs.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    <title>@ViewBag.Title</title>
</head>
<body class="site-content html">



    <header>
        <nav class="sticky">
            <div class="row">
                <ion-icon name="body-outline" class="icon-logo-big"></ion-icon>

                <ul class="main-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-action="Index" asp-controller="Article">Naujienos</a></li>
                        <li><a asp-action="Index" asp-controller="Event">Renginiai</a></li>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li><a asp-action="Index" asp-controller="Admin">Admin</a></li>
                        }
                    }
                    <li><a asp-controller="Home" asp-action="AboutUs">Apie Mus</a></li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>
    </header>

    <div class="render-body">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="row">


            <ul class="footer-nav">
                <li><a asp-controller="Home" asp-action="Privacy">Privatumo Politika</a></li>
                <li><a href="#">Bendradarbiavimas</a></li>
                <li><a href="#">Įsakymai Ir Įstatymai</a></li>
                <li>

                </li>
            </ul>

        </div>
        <div class="row">
            <div class="contact">
                <p>Kontaktai:</p>
                <p>El.Paštas: lietuvosktd@gmail.com</p>
                <p>Adresas : Eivenių g. 2, Kaunas.</p>
                <p>
                    Mus galite rasti facebook:
                    <a href="https://www.facebook.com/Lietuvosktd/" target="_blank">
                        <ion-icon name="logo-facebook" class="facebook-icon"></ion-icon>
                    </a>
                </p>
            </div>
        </div>



        <div class="row">
            <p>
                Copyright &copy; 2020, Lietuvos kineziterapeutų draugija
            </p>
        </div>
    </footer>

    <script src="~/vendors/js/jquery.min.js"></script>
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/vendors/js/jquery.waypoints.min.js"></script>
    <script src="~/js/script.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PhysicalTherapyProjectV2/Views/Shared/_LayoutIndex.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="lt">
<head>
    <link rel="stylesheet" type="text/css" href="~/vendors/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/grid.css">
    <link rel="stylesheet" type="text/css" href="~/css/main-style.css">
    <link rel="stylesheet" type="text/css" href="~/css/index-style.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
</head>
<body class="site-content">

    <header class="index-header">
        <nav>
            <div class="row">
                <ion-icon name="body-outline" class="icon-logo-big"></ion-icon>
                <ul class="main-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-action="Index" asp-controller="Article">Naujienos</a></li>
                        <li><a asp-action="Index" asp-controller="Event">Renginiai</a></li>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li><a asp-action="Index" asp-controller="Admin">Admin</a></li>
                        }
                    }
                    <li><a asp-controller="Home" asp-action="AboutUs">Apie Mus</a></li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>

        <div class="hero-text-box">
            <h1>Lietuvos kineziterapeutų draugija</h1>
            <h2>Lithuanian Physiotherapy Association</h2>
            <a class="btn btn-full" asp-action="Registration" asp-controller="Authorization">Prisijunk prie mūsų</a>
            <a class="btn btn-ghost" href="#">Sužinok daugiau</a>
        </div>

    </header>
    <div>
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="row">


            <ul class="footer-nav">
                <li><a asp-controller="Home" asp-action="Privacy">Privatumo Politika</a></li>
                <li><a asp-controller="Home" asp-action="Partnership">Bendradarbiavimas</a></li>
                <li><a href="#">Įsakymai Ir Įstatymai</a></li>
                <li>

                </li>
            </ul>

        </div>
        <div class="row">
            <div class="contact">
                <p>Kontaktai:</p>
                <p>El.Paštas: lietuvosktd@gmail.com</p>
                <p>Adresas : Eivenių g. 2, Kaunas.</p>
                <p>
                    Mus galite rasti facebook:
                    <a href="https://www.facebook.com/Lietuvosktd/" target="_blank">
                        <ion-icon name="logo-facebook" class="facebook-icon"></ion-icon>
                    </a>
                </p>
            </div>
        </div>



        <div class="row">
            <p>
                Copyright &copy; 2020, Lietuvos kineziterapeutų draugija
            </p>
        </div>
    </footer>

    <script src="~/vendors/js/jquery.min.js"></script>
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script src="~/vendors/js/jquery.waypoints.min.js"></script>
    <script src="~/js/waypoints.js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

PhysicalTherapyProjectV2/Views/Shared/_exampleLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhysicalTherapyProjectV2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/navigationBar.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhysicalTherapyProjectV2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PhysicalTherapyProjectV2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>